### ISSUE TITLE
Horizontal right alignment with wide source overview bar

### ISSUE THREAD

**Issue by Parsee1** [buchizo/ClaudiaIDE#101]
I'm using map mode for vertial scroll bar in VS2019.
Is it possible to have the background image aligned to the left of the source overview bar?
See pic:
![image](https://user-images.githubusercontent.com/9153025/138280645-01edc2f1-5bc0-40b7-bc40-92a64996e20c.png)

**Comment by buchizo** [comment]
I don't want to do re-calc size on resizing, personally. I added new ViewPortPointX/ViewPortPointY properties for relative position in ViewPort.
