### ISSUE TITLE
background image jump when scrolling

### ISSUE THREAD

**Issue by cow03haha** [buchizo/ClaudiaIDE#105]
when i scorll in editor, the background image will jump, i fine the [issue](https://github.com/Meowtrix/MoeIDE/issues/14) in other background plugin that has same problem, i think it's my visual studio problem, but i have no idea how to solve this.

visual studio 2019 Community version: 16.11.5
plugin version: 3.0.4

![preview](https://i.gyazo.com/85d4bdcef9c648ae2a675ba29f8365c1.gif "preview")

**Comment by buchizo** [comment]
Could you checked `Use Hardware graphics acceleration if available` option?
![image](https://user-images.githubusercontent.com/1254213/139801031-6e1a2c4b-dfa1-43e5-a8da-7ee62cdc9ab3.png)

**Comment by cow03haha** [comment]
it work, thx
