### ISSUE TITLE
Not running smoothly on the latest version of VS2019

### ISSUE THREAD

**Issue by fawdlstty** [buchizo/ClaudiaIDE#107]
老版本vs能正确运行claudiaide，更新到最新版本vs后出现不流畅问题，具体复现方式是，设置背景后滑动滚轮，使得代码页面上下滚动，然后整个ide就有明显不流畅感。

The old version vs can run claudiaide correctly, updated to the latest version of VS after the fluent problem, the specific way of reproduction is to set the background after sliding wheel, so that the code page scrolling up and down, and then the whole IDE has a clear sense of not fluent.

version: vs2019 community 16.11.7

**Comment by buchizo** [comment]
Could you check `Use hardware graphic acceleration if available` option in Visual Studio option dialog?

![image](https://user-images.githubusercontent.com/1254213/143794365-0d502ad7-b435-456e-bf6e-4cb24d261fb3.png)

**Comment by fawdlstty** [comment]
it's ok, thank you
