### ISSUE TITLE
Not Respecting Several Settings

### ISSUE THREAD

**Issue by Chiramisu** [buchizo/ClaudiaIDE#108]
The following settings are not being respected (i.e. not working):

- **Layout**
  - Image Stretch
  - Max Height
  - Max Width
- **SlideShow**
  - Update interval

Furthermore, it seems I have to restart VS for any changes to take effect.

**Comment by buchizo** [comment]
@Chiramisu 

> Layout

see also [this issue](https://github.com/buchizo/ClaudiaIDE/issues/89)

> SlideShow

work fine in my environment. Could you share your settings and details to me?
