### ISSUE TITLE
Configuration is Unavailable for Visual Studio Enterprise 2022 17.0.4

### ISSUE THREAD

**Issue by Coscotex101** [buchizo/ClaudiaIDE#113]
It installs fine and I can see the default image.

However, I can't find "ClaudiaIDE" anywhere on **Tools => Options**

![image](https://user-images.githubusercontent.com/48105603/151464948-38237b96-1a63-4503-95a4-7890e7bb7ba8.png)
 So I'm stuck with the default image

**Comment by buchizo** [comment]
@Coscotex101 

A default settings is config.txt file in Visual Studio extensions install path such as `C:\Users\_username__\AppData\Local\Microsoft\VisualStudio\17.0______\Extensions\__unique_id___` folder.
You can modify default image path of `BackgroundImageAbsolutePath` property. (should escape directory separator to `\\`.) 

And ClaudiaIDE option page using Visual Studio feature. I guess your Visual Studio environment or setup issue cause ClaudiaIDE option page problem in this case. Could you re-install VSIX?
