### ISSUE TITLE
Cant change Background

### ISSUE THREAD

**Issue by Scroxl** [buchizo/ClaudiaIDE#116]
Hello, i have selected a background 2 weeks ago and now i cant change it. I have tried to: 
- reinstall ClaudiaIDE,
- unselect the background,
- select the other background i want to have..
..but nothing changes.

The other background i selected worked once.
Even after the reinstall the background is already the same.
**Correct me if i missed something here.**

![backg1](https://user-images.githubusercontent.com/102724918/161010381-986d00d8-6f86-489a-9827-63ceca438008.PNG)
![backg3](https://user-images.githubusercontent.com/102724918/161010375-ca012da3-fc76-41e9-933f-97eea04bc310.PNG)
![backg2](https://user-images.githubusercontent.com/102724918/161010379-b22e0950-ef0e-4212-9b8d-92f867316715.PNG)

**Comment by Scroxl** [comment]
I tried to change the background manually through the config.txt located in 
`C:\Users\_username__\AppData\Local\Microsoft\VisualStudio\17.0______\Extensions\__unique_id___`
and now i see a line at the top of the background i want, but the anime figur is still there.

![backg4](https://user-images.githubusercontent.com/102724918/161013240-e57bc6c9-a703-4304-9142-816b926da7ed.PNG)
its pretty hard to see tho.
should i reinstall visual studio for this?

**Comment by buchizo** [comment]
@Scroxl 
If you find `.claudiaideconfig` file in solution's folder, remove it. That file is specific settings for same folder's Visual Studio solution and priority high compare than general settings (in option menu).

**Comment by Scroxl** [comment]
> @Scroxl If you find `.claudiaideconfig` file in solution's folder, remove it. That file is specific settings for same folder's Visual Studio solution and priority high compare than general settings (in option menu).

i did that, clicked on another project, the background changed and when i went back to my project, it stayed. 
**Thanks!**
