### ISSUE TITLE
Cannot display the gif in the vs2019

### ISSUE THREAD

**Issue by yuantianle** [buchizo/ClaudiaIDE#117]
Hi,

Do you know why those functions have been forbidden?
![image](https://user-images.githubusercontent.com/61530469/163628067-2adc20fd-a9f8-448a-9f79-b6b0f8f15348.png)

Here is my setting:
![image](https://user-images.githubusercontent.com/61530469/163628365-a891bef1-e47d-46f0-8072-2b6becc43148.png)

Thank you!

**Comment by buchizo** [comment]
@yuantianle 
If you find .claudiaideconfig file in solution's folder, remove it. That file is specific settings for same folder's Visual Studio solution and priority high compare than general settings (in option menu).

**Comment by yuantianle** [comment]
Thank you for your quick reply! Do you think it is possible that display the dynamic gif in VS2019?

**Comment by buchizo** [comment]
is dynamic gif means animated gif? ClaudiaIDE do not support animated gif yet.
