### ISSUE TITLE
The text editor image do not show up

### ISSUE THREAD

**Issue by quea** [buchizo/ClaudiaIDE#119]
I am using the ClaudiaIDE 3.07 version and visual studio 2022. The main window works well but when i open another new window, the image does not show up. I try uninstalling and intall it again but it does not work.How can i fix this ? 
<img width="1468" alt="111111" src="https://user-images.githubusercontent.com/9460623/174433269-853780f6-0bce-44eb-8839-845e7b8792a2.png">

**Comment by buchizo** [comment]
@quea  Could you tell me your settings of ClaudiaIDE?

**Comment by quea** [comment]
Thank you.This is my settings of ClaudiaIDE.
![22222](https://user-images.githubusercontent.com/9460623/174449196-6a255071-06eb-414d-b9e8-95c12dc8ff55.png)

**Comment by buchizo** [comment]
@quea Could you try set `Base tile image relative width` and `Base tile image relative height` properties to `1`?

**Comment by quea** [comment]
Oh it works! Thanks for your help!🤞
