### ISSUE TITLE
Issues with changing tabs and slides

### ISSUE THREAD

**Issue by daKuleMune** [buchizo/ClaudiaIDE#120]
There is an issue when the Image Background Type is set to Slideshow, after the slide move to the next image: Tabs that were not active when the image slide went to the next image will now have a small version of the image and if opacity is set it will double the opacity because they are overlayed on top of each other.
Cool addon but I cannot use the slideshow feature without the code becoming hard to read or the opacity of images way half what I want them to be in the whole editor.
Another setting that may be way this is happening is the Expand to IDE being true.

**Comment by buchizo** [comment]
@daKuleMune Fix on 3.0.8

**Comment by daKuleMune** [comment]
Wow, thanks that fixed it!
