### ISSUE TITLE
The saving location of .claudiaideconfig when in CMake projects

### ISSUE THREAD

**Issue by cuteday** [buchizo/ClaudiaIDE#122]
When I save the configuration for a CMake project (the project folder is directly opened with VS), the .claudiaideconfig file is saved to the parent directory of the solution folder, which seems to me is different than expected.
The file is saved to the right location when using .sln solutions, as I tested. 

Please close this if this is not considered a bug. 
And thanks for this great extension!

Env: version 3.0.8 in VS 17.2.6

**Comment by buchizo** [comment]
Thank you for your report. I fixed on 3.0.9
