### ISSUE TITLE
How to remove the random small image located at bottom-right?

### ISSUE THREAD

**Issue by jeremy-marmol-swi** [buchizo/ClaudiaIDE#130]
I noticed there is a random image appearing at the bottom-right of the panel. How can this be removed?

![image](https://user-images.githubusercontent.com/84544317/190243863-c48a13dd-533e-4a67-8a78-fe82a2058a60.png)

**Comment by jeremy-marmol-swi** [comment]
I uninstalled this extension but the bg image didn't disappear. How can I completely remove this extension as well as its settings?

**Comment by Unthrottled** [comment]
I think this one is on me.

[You need to go to the Content Settings menu](https://github.com/doki-theme/doki-theme-visualstudio#content-settings) and set `DrawSticker` to `false` and that should fix the issue.

**Comment by buchizo** [comment]
I guess that image and feature is not this ClaudiaIDE extension's feature. Could you check for your [The Doki Theme: Visual Studio](https://github.com/doki-theme/doki-theme-visualstudio)?
