### ISSUE TITLE
Nothing displayed while using SINGLEWEB or WEBAPI

### ISSUE THREAD

**Issue by Klutton** [buchizo/ClaudiaIDE#131]
I thought that it was my problem while using webapi but even i copied the url of api json, there was nothing showing up.
Is it because that the url has a special pattern?

https:\/\/tuapi.eees.cc\/dongman\/pc\/TUAPI-EEES-CC--954391666.jpg

key=img
api endpoint=https://tuapi.eees.cc/api.php?category=dongman&type=json

**Comment by buchizo** [comment]
@Klutton  In my case on my environment, its url and web api is no problem.  Could you try other url? 

e.g.
api endpoint: https://azure.moe/api/image
key: url

And your environment require web proxy?

**Comment by Klutton** [comment]
wow, the information you provided is usable. However I can view the json and url the website i use on edge, but can't be seen on vs.
I noticed that the api you provided has a standard url pattern while mine is a bit odd but still can access in browser, can you try to match the url?
I couldn't type the format of the url, just visit this website and you'll see how it works.

**Comment by Klutton** [comment]
if you can't access the website, maybe you need proxy that connects to China

**Comment by buchizo** [comment]
> I couldn't type the format of the url, just visit this website and you'll see how it works.

I can show image of `https://tuapi.eees.cc/dongman/pc/TUAPI-EEES-CC--954391666.jpg` and api on my Visual Studio and browser.

**Comment by Klutton** [comment]
(⊙﹏⊙)god... mine appeared too, maybe I should try to reboot my computer and then send issue here.
I appreciate your help, and I'm sorry for the inconvenience...

**Comment by Klutton** [comment]
oops, it appears again!
If vs is started by unity, the ide doesn't works, and if I start vs from desktop, the photo loads properly
![image](https://user-images.githubusercontent.com/113648660/190633544-d836b110-e709-4123-bd69-04893176242a.png)

**Comment by buchizo** [comment]
@Klutton Ok, I understood  and reproduce issue in my environment.

**Comment by buchizo** [comment]
I guess fix this issue in ver3.1.5.

**Comment by Klutton** [comment]
😊👌
