### ISSUE TITLE
[Feature Request] Add keyboard shortcut to set image transparency to 0

### ISSUE THREAD

**Issue by TheWolfWraith** [buchizo/ClaudiaIDE#134]
Would be nice for some situations

**Comment by TheWolfWraith** [comment]
Something like a toggle if possible. Hitting the button sets transparency to 0. Hitting it again reverts it to whatever it was set at.

**Comment by buchizo** [comment]
Added `Toggle Background Image Visibility` menu in ver3.1.6.
And I allocated shortcut key binding for that menu, however that shortcut does not work in the text editor by default. If you want enable it in a text editor, you should re-allocated shortcut in Visual Studio option.
