### ISSUE TITLE
ClaudiaIDE package did not load correctly

### ISSUE THREAD

**Issue by KyleMuncie** [buchizo/ClaudiaIDE#137]
![Screenshot 2022-10-07 080409](https://user-images.githubusercontent.com/57012333/194585503-694143e2-e595-4da5-9964-e76a5f45063a.png)

ClaudiaIDE not working. Potentially something I must have updated? Does anyone know how to fix this? I am using Microsoft Visual Studio 2022. 
I've tried everything here [https://stackoverflow.com/questions/17574089/how-can-i-fix-the-microsoft-visual-studio-error-package-did-not-load-correctly?page=1&tab=scoredesc#tab-top](url)

**Comment by buchizo** [comment]
@KyleMuncie 
Could you provide `ActivityLog.xml` to me? (path is in it dialog)
And what is your Visual Studio detail version? (e.g. Ver 17.3.5 as follows:
![image](https://user-images.githubusercontent.com/1254213/194609299-0c0a7faa-9cb9-4fe9-bcb2-ae68fe71500d.png)

**Comment by KyleMuncie** [comment]
Version: 17.2.6:
I changed the XML file to a txt file in order to send.
[ActivityLog.txt](https://github.com/buchizo/ClaudiaIDE/files/9735865/ActivityLog.txt)

Thanks!

**Comment by buchizo** [comment]
@KyleMuncie 
I guess this issue's case is depends from VSSDK version. I'll backdate package. 
Or your VIsual Studio update latest version (17.3.5), if possible.

**Comment by KyleMuncie** [comment]
@buchizo Updating to 17.3.5 solved my problem. Thank you!!!!!!
