### ISSUE TITLE
Windows 10 150% Scaling Produces HUGE Image

### ISSUE THREAD

**Issue by stricq** [buchizo/ClaudiaIDE#14]
On a 4K monitor with Windows 10 at 150% scaling, the images are HUGE and  you can only see a small corner of the full image.

**Comment by buchizo** [comment]
Could you send screenshot to me? However, I think it is default behavior on Windows DPI scaling.

**Comment by stricq** [comment]
![claudiaide huge background](https://cloud.githubusercontent.com/assets/1395862/16572112/18a0669e-4222-11e6-887c-1f7cfad18abc.png)

Here is a screenshot.

**Comment by stricq** [comment]
![kyuubackgrounds normal](https://cloud.githubusercontent.com/assets/1395862/16572444/ee523c74-4225-11e6-874f-4a14fb664d3a.png)

Here is the same image using KyuuBackgrounds.  You have the slideshow, I'd really like to see that working.  :-)

**Comment by buchizo** [comment]
I added image stretch feature. 
https://github.com/buchizo/ClaudiaIDE/releases/tag/Release1.23.1

**Comment by stricq** [comment]
It works perfectly now.  Thanks!
