### ISSUE TITLE
Tiled config not courrectly 

### ISSUE THREAD

**Issue by dev-nujen** [buchizo/ClaudiaIDE#140]

**Comment by dev-nujen** [comment]
tiled config not courrectly for other image background

**Comment by buchizo** [comment]
@dev-nujen
TileMode shoud use with ViewPortHeight or ViewPortWidth and these values is 0 < n < 1.
If you set to 1 (1 is default value) in ViewPort__, acctually background image is 1 tile. (1 = 100%)
