### ISSUE TITLE
Image partially covered up

### ISSUE THREAD

**Issue by scottcantwell** [buchizo/ClaudiaIDE#141]
Image partially covered up by the scrollbar on the right and by the bottom of the text editor.

**Comment by buchizo** [comment]
@scottcantwell Could you provide more details?

**Comment by scottcantwell** [comment]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/90006729/204180428-5424a82f-519d-4d48-81dc-be9f1e6de51a.png)

**Comment by buchizo** [comment]
Hmm, if your ViewPort___ options value is not 0 or 1 in ClaudiaIDE option of VS option dialog, could you ajust it?

**Comment by scottcantwell** [comment]
I adjusted it and it worked. Thank you!
