### ISSUE TITLE
Picture can't be loaded via WebApi, may caused by low network speed

### ISSUE THREAD

**Issue by Klutton** [buchizo/ClaudiaIDE#145]
Hi, I am trying to use this api to load pictures

**NSFW**

`
https://api.lolicon.app/setu/v2
`

However, since some kind of network problem, the picture itself loads slowly on my firefox.

So I was wondering if it was caused by low network speed, please try it on your computer qwq.

the key is 

`
original
`

If it runs properly on your computer, I think there might be some problem on ImageDownloader.

Might be some kind of time-out issue.

**Comment by buchizo** [comment]
Maybe fix it for ver3.1.12
