### ISSUE TITLE
With `Expand to IDE` on, the dropdown list and breakpoint sidebar will show their background color over the image

### ISSUE THREAD

**Issue by n0099** [buchizo/ClaudiaIDE#153]
It happens when I toggle to another file editor in tabs:
![image](https://user-images.githubusercontent.com/13030387/219871163-a02d8455-4bd2-475c-b619-c3221541210c.png)
And the image in the editor firstly shown after launching IDE, or opening then closing the `Tools-Options-ClaudiaIDE` window, is still able to display over the dropdown list and breakpoint sidebar:
![image](https://user-images.githubusercontent.com/13030387/219871156-45f0bffb-afbe-4472-825c-46ed1fcc32e2.png)

**Comment by buchizo** [comment]
maybe fix it on 3.1.17

**Comment by n0099** [comment]
Now progress bar is disappeared(in transparent?):
![image](https://user-images.githubusercontent.com/13030387/219899622-1411e182-1f09-4e8a-8db2-286aa359f068.png)

**Comment by n0099** [comment]
Also for some floating windows:
![image](https://user-images.githubusercontent.com/13030387/219905658-2c6c52b6-49ae-40a6-9b3d-7e61d7cf87e2.png)

**Comment by buchizo** [comment]
@n0099 

> Now progress bar is disappeared(in transparent?):

Yes, ver3.1.17 change to transparent of scrollbar background at `expand to IDE`.

> Also for some floating windows:

ClaudiaIDE is set to transparent for main window and only text editor area (and it chidren UIElement) at enabled `expand to IDE` option.

fig.1
![image](https://user-images.githubusercontent.com/1254213/219932134-54c9c9a8-8545-4002-8485-03b72e759b48.png)

If it using option with `Transparency Theme` or `Dark Transparency Theme` or other color theme,  these maybe set transparent to other backgrounds. e.g. dropdown list, exception settings, title bar, menu bar, and others. I guess this behaviors cause in those color themes.

fig. 2
![image](https://user-images.githubusercontent.com/1254213/219932214-c7316f7c-7994-4ee8-925f-29f356e36688.png)

**Comment by n0099** [comment]
> Yes, ver3.1.17 change to transparent of scrollbar background at `expand to IDE`.

Is it possible to only set the scrollbar thumb as transparency? If not may you add an option to allow me to disable this behavior (for horizontal and vertical respectively)?

> If it using option with `Transparency Theme` or `Dark Transparency Theme` or other color theme, these maybe set transparent to other backgrounds. e.g. dropdown list, exception settings, title bar, menu bar, and others. I guess this behaviors cause in those color themes.

I'm using [Jason-Zhang.darktranparencytheme](https://marketplace.visualstudio.com/items?itemName=Jason-Zhang.darktranparencytheme), now it looks like:
![image](https://user-images.githubusercontent.com/13030387/219970570-498715cd-305b-4189-843d-d2ee0e9a4511.png)

**Comment by buchizo** [comment]
> Is it possible to only set elements except the scrollbar thumb as transparency? If not may you add an option to allow me to optout this behavior (for horizontal and vertical respectively)?

Oops, I'll fix it.

> I'm using [Jason-Zhang.darktranparencytheme](https://marketplace.visualstudio.com/items?itemName=Jason-Zhang.darktranparencytheme), now it looks like:

You can try customize theme from Dark Transparency Theme using [Color Theme designer](https://marketplace.visualstudio.com/items?itemName=idex.colorthemedesigner2022)

**Comment by rayfalling** [comment]
Same problem progress bar is disappeared
I also use resharper hint, When expend to IDE set to true, hint background also be transparency.
Maybe user can decide whether set all backgroud transparency?

**Comment by n0099** [comment]
> I also use resharper hint

Which hint? Do you mean [type inlay](https://www.jetbrains.com/help/resharper/Inline_Parameter_Name_Hints.html)?
You can change its color in `Options-Environment-Fonts and Colors`:
![image](https://user-images.githubusercontent.com/13030387/220080529-36852496-5593-4f58-accd-fa73e61dda38.png)
I've changed lots of these color palettes to improve contrast of texts.

**Comment by n0099** [comment]
> Resharper's Inlay Hint background

Try set it to automatic(as my screenshot above)

**Comment by buchizo** [comment]
@rayfalling resharper hint means like as IntelliSence? Could you share screen shot to me?

**Comment by rayfalling** [comment]
Correct:
![image](https://user-images.githubusercontent.com/13343271/220094845-003caaac-8b08-42a7-ac16-1c1f154bd258.png)
Wrong:
![image](https://user-images.githubusercontent.com/13343271/220095836-c8d978fa-5682-472b-ba6e-8f251274dc0e.png)

**Comment by rayfalling** [comment]
I think this is the same problem with scrollbar disappear because these elements' background is set to transparency?

**Comment by buchizo** [comment]
I guess yes. I'll fix its.

**Comment by buchizo** [comment]
Fix scrollbar thumb transparent for 3.1.18
![image](https://user-images.githubusercontent.com/1254213/220172387-dd733fc4-863a-4933-9c51-2eff4f2a3201.png)

**Comment by n0099** [comment]
> Correct: ![image](https://user-images.githubusercontent.com/13343271/220094845-003caaac-8b08-42a7-ac16-1c1f154bd258.png) Wrong: ![image](https://user-images.githubusercontent.com/13343271/220095836-c8d978fa-5682-472b-ba6e-8f251274dc0e.png)
> 
> These two can appear at the same time ![image](https://user-images.githubusercontent.com/13343271/220096112-45f3e7f6-6520-4233-b781-20d7f36b2a4a.png)

They are same in my side:
![image](https://user-images.githubusercontent.com/13030387/220214880-77d55ece-e0d6-48d8-875a-e96489a46fca.png)
Which theme do you use?

> > If it using option with `Transparency Theme` or `Dark Transparency Theme` or other color theme, these maybe set transparent to other backgrounds. e.g. dropdown list, exception settings, title bar, menu bar, and others. I guess this behaviors cause in those color themes.
> 
> I'm using [Jason-Zhang.darktranparencytheme](https://marketplace.visualstudio.com/items?itemName=Jason-Zhang.darktranparencytheme), now it looks like:

**Comment by n0099** [comment]
@buchizo Can you remove the transparent background of the +/- collapse control near the line numbers column? It's hard to distinguish whether collapsed or not:
![image](https://user-images.githubusercontent.com/13030387/220518170-3ca102f8-ce3d-4250-a31c-f7077073f512.png)
![image](https://user-images.githubusercontent.com/13030387/220518185-4c1cd325-2e14-4287-9f67-b987119c191c.png)

**Comment by buchizo** [comment]
> Can you remove the transparent background of the +/- collapse control near the line numbers column? It's hard to distinguish whether collapsed or not:

Fix on 3.1.19
