### ISSUE TITLE
Transparency issues with VsVim and Expand IDE

### ISSUE THREAD

**Issue by tgaldi** [buchizo/ClaudiaIDE#158]
Cursor is transparent after you start entering text.

Issue is only if Expand to IDE is true. 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/17083706/228335473-255694f9-bbaa-478c-8605-51ed43384872.png">

<img width="542" alt="image" src="https://user-images.githubusercontent.com/17083706/228335674-333cdcd1-ed0d-4ee3-9048-3587eec5719f.png">

Exception popup is transparent until dragged/moved (this is probably a separate issue that doesn't seem to be affect by Expand IDE).
<img width="350" alt="image" src="https://user-images.githubusercontent.com/17083706/228350801-85797f2f-c4ec-44f4-aa43-46c63d87455a.png">

Also, with Expand to IDE false the transparency stops working correctly when debugging unless you toggle it off and on again.

**Comment by buchizo** [comment]
@tgaldi 
Probably I fixed both the problems in ver3.1.20.
