### ISSUE TITLE
幻灯片放映淡入淡出

### ISSUE THREAD

**Issue by BAT2048** [buchizo/ClaudiaIDE#162]
自动上次更新了VS之后，幻灯片的淡入淡出放映效果就失效了。
The fade - in and fade - out effect of the slide won't work the last time Autoplay was updated VS.

![image](https://user-images.githubusercontent.com/115937964/234239558-87b7ffc6-4662-41cd-bf7d-267204d34272.png)

**Comment by buchizo** [comment]
Maybe fixed it on 3.1.22

**Comment by BAT2048** [comment]
> Maybe fixed it on 3.1.22

感谢你提供这么好用的工具
Thank you for providing such a useful tool
