### ISSUE TITLE
Text editor background, sticky scroll, split window

### ISSUE THREAD

**Issue by xx790** [buchizo/ClaudiaIDE#172]
I like the background image to be aligned to the right under text editor.
(Expanding to IDE and aligning to the right - doesn't work well because side panels hide the image.
Expanding to IDE and aligning to the center - I don't like it because image might be not well aligned with panels.)

So, I have settings:
- Expand to IDE: false
- Horizontal alignment: right

When I start VS - I see it works like this:

![image](https://github.com/buchizo/ClaudiaIDE/assets/118630824/260ec29b-e84e-40d8-9ea6-8ffe8a048626)

Sticky scroll lines don't have background image.
In combination with split window this can lead to a lot of screen space without image.

Then I do the following:
1. set Expand to IDE: true and apply settings;
2. set Expand to IDE: false and apply settings.

After these steps, I see it like this:

![image](https://github.com/buchizo/ClaudiaIDE/assets/118630824/4849fc2e-1d89-4b11-80ba-dc63cc616012)

The image is shown under all screen elements and properly aligned under the editor.

There are two issues with this though:
- This doesn't persist after VS restart;
- I would've preferred to see the separator line where the window is split.

So, it would be really nice if you can make the default behavior for when it is limited to text editor - to be closer to this (edited image, can't be achieved currently):

![image](https://github.com/buchizo/ClaudiaIDE/assets/118630824/880f95db-4dda-48b5-8718-a502a90ab39a)

This should allow:
- the image to be visible over most of the screen,
- keeping split sections from blend with each other,
- being able to find the draggable splitter easily.

----

Side note:
there is also the option "Background image limit to only editor window" that sound like it might be something relevant, but I can't see it doing anything. English description is also not good, so I'm not sure what exactly it is supposed to do and whether it does it at all.

**Comment by buchizo** [comment]
If `Background image limit to only editor window` option is true and using `Expand to IDE` option, ver3.1.26 is not set to transparent for sticky scroll and split window content.

**Comment by xx790** [comment]
Maybe I didn't explain it well enough, sorry.

I don't think #174 does exactly what I needed.

| Version | Sticky scroll is transparent (with background image applied) | Split window margin is visible (no background image applied) | Image can be limited to editor |
| ------- | ---------------------------- | ------------------------------ | -------------------------------- |
| 3.1.25 `expand to IDE=False` | ❌ | ⭕ | ⭕ |
| 3.1.25 `expand to IDE=True` | ⭕ | ❌ | ❌ |
| #174 `expand to IDE=False` | ❌ | ⭕ | ⭕ |
| #174 `expand to IDE=True`, `...limit...=False` | ⭕ | ❌ | ❌ |
| #174 `expand to IDE=True`, `...limit...=True` | ❌ | ⭕❓ | ❌ |

----

Note about `Background image limit to only editor window` description:

I suggest to update this description:

> `<value>If this option is True, background image limit to only editor window.</value>`

to

> `<value>If this option is True, background image is limited only to editor window. If this option is False, [...] . This option has no effect when [...] .</value>`

----

Possible issue with `Background image limit to only editor window`:

| Background image limit to only editor window | Expand to IDE | image display |
| -------------------------------------------- | ------------- | ------------- |
| True                                         | True          | Whole IDE (can be obscured by sidebar) ❌❓ |
| False                                        | True          | Whole IDE (can be obscured by sidebar) ⭕ |
| True                                         | False         | Each Editor ⭕ |
| False                                        | False         | Each Editor ⭕ |

Because I don't understand what `Background image limit to only editor window` does exactly, I'm not sure if this is a correct behavior.

**Comment by buchizo** [comment]
Um.. maybe I was mistaken understanding root cause.
First, `Background image limit to only editor window`  option is limited for text editor only, for example if this option set to ture, [Preview Changes Window](https://learn.microsoft.com/en-us/visualstudio/ide/preview-changes?view=vs-2022) is not appear background image.

Next, I would like to add new options to the text editor's sticky scroll and content area. This new option allows you to set a background image or not that is independently  `Expand to IDE` options. Is this behavior, resolve your issue?

**Comment by xx790** [comment]
> Next, I would like to add new options to the text editor's sticky scroll and content area. This new option allows you to set a background image or not that is independently `Expand to IDE` options. Is this behavior, resolve your issue?

Yes, this sounds good. I also thought to suggest making them separate options.

> First, `Background image limit to only editor window` option is limited for text editor only, for example if this option set to ture, [Preview Changes Window](https://learn.microsoft.com/en-us/visualstudio/ide/preview-changes?view=vs-2022) is not appear background image.

I suggest following description for clarity:

> If this option is True, background image is limited only to code editor window. If this option is False, different kinds of controls with code will have background image as well.

**Comment by buchizo** [comment]
I added new two options for sticky scroll and content margin (= navigation bar, horizonal and vertical scroll bar..).

![image](https://github.com/buchizo/ClaudiaIDE/assets/1254213/12f3e90b-1e96-41b9-b371-f9301f256c64)

**Comment by xx790** [comment]
It works, awesome!
Thank you!

Split window separator disappeared in this version though:
![image](https://github.com/buchizo/ClaudiaIDE/assets/118630824/680a87ad-bde7-4511-b4dc-939091c0265b)
(It was the darker line on the very first screenshot, it is where the cursor changes to arrows.)

Most notable when both new options are False:
![image](https://github.com/buchizo/ClaudiaIDE/assets/118630824/ca83d2df-77b1-46fd-b6a1-d87ac6a841b9)

Not a big deal though - I can still find it under horizontal scrollbar area that is not transparent.
If it is difficult to toggle together with content margins - I'm fine with how it works currently, and the issue can be closed.
