### ISSUE TITLE
Image No Longer Appear in XAML Source Editor Windows

### ISSUE THREAD

**Issue by stricq** [buchizo/ClaudiaIDE#175]
The images used to appear in the XAML editor windows.  I'm not sure when this stopped, but I just noticed today because I came back to an old WPF project for modifications.

**Comment by buchizo** [comment]
@stricq 
If you do set True to `Background image limit to only editor window` option, this extension don't set background image for WPF editor.

**Comment by stricq** [comment]
Thanks, that fixed it.  Not really sure what that option does, but images now show in the XAML source editor window.
