### ISSUE TITLE
section `Pushlish` of tab `Connected Services` is unreadable

### ISSUE THREAD

**Issue by n0099** [buchizo/ClaudiaIDE#177]
https://learn.microsoft.com/en-us/visualstudio/azure/overview-connected-services#local-and-connected-configurations
![image](https://github.com/buchizo/ClaudiaIDE/assets/13030387/16ae070e-6ed0-4c59-bc0a-1c1327e4d902)
It's seems a regression introduced in `3.1.17`: https://github.com/buchizo/ClaudiaIDE/issues/153#issuecomment-1435904080

**Comment by n0099** [comment]
Also the `Find and Repalce` window: ![image](https://github.com/buchizo/ClaudiaIDE/assets/13030387/d2f752f6-60ef-4358-af43-d31567d2d1d1)

**Comment by buchizo** [comment]
@n0099  unfortunately this issue did not reproduce. If you did use other color theme (e.g. transparent theme), it have possible that is set transparent to these background.

**Comment by n0099** [comment]
https://github.com/buchizo/ClaudiaIDE/issues/153#issuecomment-1436505546

**Comment by buchizo** [comment]
ClaudiaIDE (expand to IDE option) + [Jason-Zhang.darktranparencytheme](https://marketplace.visualstudio.com/items?itemName=Jason-Zhang.darktranparencytheme)

![image](https://github.com/buchizo/ClaudiaIDE/assets/1254213/21350779-f361-4b57-8774-da596f52d8b5)

Did not reproduce.

**Comment by buchizo** [comment]
I applied  that theme.

![image](https://github.com/buchizo/ClaudiaIDE/assets/1254213/aefcf8c8-4f50-45d5-92e5-86f3eae182e0)

I guess this issues root cause is from that theme. ClaudiaIDE is unrelated.
