### ISSUE TITLE
The light theme in vs2022 themes (choosing to use system settings) has a small issue.

### ISSUE THREAD

**Issue by Jiangmitiaotiao** [buchizo/ClaudiaIDE#179]
Is there any way to modify the background color of the new blue-themed text editing box to white? The old version had a white background.
![屏幕截图 2024-01-14 171754](https://github.com/buchizo/ClaudiaIDE/assets/46468315/9dd4c93f-c211-4da4-b8c8-f4f141fd793b)

**Comment by buchizo** [comment]
fix this issue for ver 3.1.31
