### ISSUE TITLE
Sticky scroll transparency is not applied in Xaml files

### ISSUE THREAD

**Issue by xx790** [buchizo/ClaudiaIDE#184]
Follow-up to #172 

Sticky scroll is transparent for other files - as expected.
Sticky scroll is not transparent for Xaml files:

![image](https://github.com/buchizo/ClaudiaIDE/assets/118630824/6c47ba6b-01da-4a94-a943-20a35aa3747e)

**Comment by buchizo** [comment]
I fixed it by v3.1.33

**Comment by xx790** [comment]
Hmm

This made it to lose the background color from the color theme:

![image](https://github.com/buchizo/ClaudiaIDE/assets/118630824/8c3b2ed2-62eb-4bc4-a085-b1995a0fa839)

Xaml and cs files will have the same background if I disable sticky scroll transparency.

**Comment by buchizo** [comment]
maybe fixed it.

**Comment by xx790** [comment]
Thank you, the background color is fixed.

Curiously, split view works differently in xaml editor, resulting in two separate background images and visible separator:

![image](https://github.com/buchizo/ClaudiaIDE/assets/118630824/bd803787-e19d-4482-b7bf-e916584651e1)

I'm not very concerned about it though.
