### ISSUE TITLE
SlideShowImageProvider crash

### ISSUE THREAD

**Issue by xx790** [buchizo/ClaudiaIDE#187]
I think there a flaw in `SlideShowImageProvider`.
It caused VS crash by itself sometime after I deleted some images from the folder that it uses.

After `GetBitmap()` gets nonexistent file path - it calls `OnSettingChanged(null, null)`, but that doesn't work as expected.

I'd suggest extracting image paths refresh into a separate method and call that instead of `OnSettingChanged`.

**Comment by buchizo** [comment]
I fixed it by v3.1.34

**Comment by xx790** [comment]
Thank you.
It seems to work fine now.
