### ISSUE TITLE
Issue/Bug: Color scheme changes

### ISSUE THREAD

**Issue by gamagan** [buchizo/ClaudiaIDE#197]
Hello,

I tried to use this extension on the latest Visual Studio (v17.10 Preview 7).  The extension has an issue, and I'm wondering if it's a known problem, or not.

I use a dark color scheme, and I then make the background darker than normal. When I enable the extension, it changes my color scheme, slightly. It makes the background lighter, which then causes the bg and font colors wash out into eachother.

Is the fact that it changes the background (don't know about other colors) a known issue? I'd like to be able to use this extension, but I can't because of this problem.

Hope all is well
Regards

**Comment by buchizo** [comment]
@gamagan could you share your screen shorts about before install and after installed?

**Comment by gamagan** [comment]
Yeah. I should have included a screenshot.

The left is my normal color scheme. The right is after enabling Claudia. 

![claudia](https://github.com/buchizo/ClaudiaIDE/assets/9970152/6645862d-de4b-4ed9-84ca-47f1f2ab0800)

**Comment by buchizo** [comment]
@gamagan Thank you so much.
This behavior is by design because ClaudiaIDE set transparent to default background color, just now.

If you want to more darken or you want of background color, your specify image include background.

**Comment by gamagan** [comment]
I didn't fully understand your last comment.

A) Are you saying that there is an option to use the normal background color? 
B) Or are you saying that, to have the normal background color, then the image itself needs to have the desire background color?

If it's B, and I want a "small image" on the bottom right corner, then that means I have to make a big file with the background color, and then put the small image on the big file. Is this correct?

**Comment by buchizo** [comment]
It's B.

> If it's B, and I want a "small image" on the bottom right corner, then that means I have to make a big file with the background color, and then put the small image on the big file. Is this correct?

That's right. However I maybe update about support default background color option.

**Comment by gamagan** [comment]
> That's right. However I maybe update about support default background color option.

That would be cool.

Thank you for the reply.

**Comment by buchizo** [comment]
I added `Editor background color` option property in ver3.1.39.
