### ISSUE TITLE
Does not install to Visual Studio 2017 RC

### ISSUE THREAD

**Issue by buchizo** [buchizo/ClaudiaIDE#20]
Current version (1.25.2) doesn not install to Visual Studio 2017 RC.
If you was install it, error occurred as follows:

2016/12/19 04:44:58 - Install error: System.IO.FileNotFoundException: Unable to find the specified file.   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by metalglove** [comment]
I have the same problem but with all exstensions for visual studio 2017 RC. atm i am trying to reinstall visual studio.

**Comment by galloperx** [comment]
Not sure if it's the same issue, but in my case (also in 2017RC) it's half-working: I can [Enable] Claudia IDE in tools, then is asks for restart of Visual Studio and then it seems to work for the full duration of VS running, but after another restart (say the next time I need to work) it's in [Disabled] state again.

**Comment by IIARROWS** [comment]
It's working for me in the latest RC (February 8th)

**Comment by buchizo** [comment]
Maybe this issue was fixed by VS2017RTM
