### ISSUE TITLE
如果手动将路径设为不存在的图片路径，会导致IDE崩溃

### ISSUE THREAD

**Issue by yinyue200** [buchizo/ClaudiaIDE#21]
另外希望背景图片展示方式中增加 “Disable” 方便暂时关闭背景图片

Thanks

**Comment by buchizo** [comment]
@yinyue200 Hi,
Would you want to need about switch of disable/enable in ClaudiaIDE extensions option page? E.g. Are you want to disable temporary? If you want that, you can disable in the 'extensions and updates' dialog box.
