### ISSUE TITLE
May I ask which anime this character comes from？

### ISSUE THREAD

**Issue by XzMitsui** [buchizo/ClaudiaIDE#211]
![image](https://github.com/user-attachments/assets/f9f366d0-d19d-4574-958b-86d192d87385)

**Comment by buchizo** [comment]
She is `Claudia Madobe` (`クラウディア窓辺`), It was Microsoft Japan official calactor, but currently it has disappeared.. X(

see also:

https://ja.wikipedia.org/wiki/%E3%82%AF%E3%83%A9%E3%82%A6%E3%83%87%E3%82%A3%E3%82%A2%E3%83%BB%E7%AA%93%E8%BE%BA
https://dic.pixiv.net/a/%E3%82%AF%E3%83%A9%E3%82%A6%E3%83%87%E3%82%A3%E3%82%A2%E7%AA%93%E8%BE%BA

**Comment by XzMitsui** [comment]
@buchizo Ok，thanks so much
