### ISSUE TITLE
Issue with VS Ent. 2017

### ISSUE THREAD

**Issue by DiomedesDominguez** [buchizo/ClaudiaIDE#24]
I'm getting this error every time I try to access the option of ClaudiaIDE. I tried to uninstall and install but nothing changed.

![jkasbff](https://cloud.githubusercontent.com/assets/4379316/25584367/b0858a42-2e63-11e7-9fe4-50181fda4dce.PNG)

**Comment by buchizo** [comment]
@DiomedesDominguez ,

Would you try "devenv /setup" in cmd.exe as follows?

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe" /setup

* modify path according to your environment.

**Comment by DiomedesDominguez** [comment]
I did it but nothing changes.
