### ISSUE TITLE
Updated to v1.28, IDE crashes when opening code window

### ISSUE THREAD

**Issue by dev-cdd** [buchizo/ClaudiaIDE#26]
![vs2017-claudiaide-crash](https://user-images.githubusercontent.com/222110/27031432-355a4ba4-4f3e-11e7-842f-d62906015ab1.png)

**Comment by buchizo** [comment]
@dev-cdd  Would you like to send details log to me? e.g. EventViewer's devenv.exe of application log

**Comment by dev-cdd** [comment]
[claudia-eventviewer-log.txt](https://github.com/buchizo/ClaudiaIDE/files/1068427/claudia-eventviewer-log.txt)
Attaching two event viewer entries.

**Comment by buchizo** [comment]
I uploaded 1.28.2.
I guess this issue occurred when background image not exist. I hope fixed this problem using this version.

**Comment by dev-cdd** [comment]
[claudia-eventviewer-log.txt](https://github.com/buchizo/ClaudiaIDE/files/1068825/claudia-eventviewer-log.txt)
Updated to 1.28.2 - crash still occurs, updated eventviewer text (attached).

**Comment by Leuconoe** [comment]
same issue.
I get an error even if I have a background image.  1.28.2

**Comment by buchizo** [comment]
@dev-cdd , @Leuconoe Thx.
Hmm ... 1.28.x code include some problems depends on environment, personally. Just now, I not have solutions, but cause is async/await update. I will release 1.28.3 after few hours from revert to 1.27 based code.

**Comment by buchizo** [comment]
@dev-cdd , @Leuconoe If you try use 1.28.3 and remove this issue, I'll close this.

**Comment by Leuconoe** [comment]
Resolved.
Thank you.
