### ISSUE TITLE
VS2013 ultimate Installing error.

### ISSUE THREAD

**Issue by PominoBell** [buchizo/ClaudiaIDE#28]
vs2013 ultimate : VSIXInstaller. NoApplicableSKUsException: this extension cannot be installed on any currently installed product.

**Comment by DragonQuestHero** [comment]
try to install VS2015 then install the ClaudiaIDE

**Comment by PominoBell** [comment]
......OK, maybe it's a good idea.

**Comment by buchizo** [comment]
I added type of Ultimate edition to Install Targets. Would you like to re-install ver 1.28.5?

**Comment by PominoBell** [comment]
The version 1.28.5 works well. Thanks you.
