### ISSUE TITLE
Background image component is rendered on top of text, not under it

### ISSUE THREAD

**Issue by noorus** [buchizo/ClaudiaIDE#3]
The background image is positioned (as in Z-index?) on top the text UI layer, instead of under it.
So with a large "adornment" image, it might block long lines of code, or at least make them much harder to read.
Another related problem is that in Visual Studio 2013, the image layer is drawn over the Peek Definition helper window which opens with Alt+F12. The image blocks mouse clicks to the Peek Definition window's close button, so the only way to get rid of the peek definition window is to close and reopen the document.
![untitled-1](https://cloud.githubusercontent.com/assets/1813374/5061770/42ac10e0-6dae-11e4-8a1b-8e77c72cdd56.jpg)

**Comment by celeron533** [comment]
Issue comes again in v1.15 with vs2013
![image](https://cloud.githubusercontent.com/assets/3608762/8868096/fc076866-3205-11e5-92e1-9ff9f89dba87.png)
