### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by winromulus** [buchizo/ClaudiaIDE#30]
Submitting this request for improvement:

If a background image is picked and docked to bottom, when scrolling the image scrolls with the text and then snaps back to position. This results in a lot of flickering (extremely distracting) if scrolling through the content of a large file.
An improvement for this would be awesome (only reason I had to disable the extension for larger projects).

**Comment by buchizo** [comment]
I agree that. I know this case, however I not have solutions now. ClaudiaIDE do ajust position of background image when changed of editor position in VS. e.g. window size change or scroll down/up in editor. VS is notify new position to ClaudiaIDE. But There is a case that it is misled actually position. That is flickering. In my case, this issue occurred in lower graphic performance pc. I was continuus to tackre improved performance, but I couldn't solve it, just now. If you have any ideas, please tell me it. Thanks.

**Comment by buchizo** [comment]
I'll be closed this issue.
