### ISSUE TITLE
How to change output's transparency?

### ISSUE THREAD

**Issue by misaka00251** [buchizo/ClaudiaIDE#33]
Here: https://imgur.com/a/w7tAwKJ
Can't found any settings in color editor.... and the stuff in "All Elements" just confused me :/

**Comment by buchizo** [comment]
I think some window can't modify color via theme editor. If you want, report to theme editor proj. (e.g. https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2017ColorThemeEditor )
