### ISSUE TITLE
 Xaml window background does not match IDE

### ISSUE THREAD

**Issue by TobiasTao** [buchizo/ClaudiaIDE#34]
cs window is ok：
![image](https://user-images.githubusercontent.com/37654563/47255042-0db94600-d49d-11e8-95ed-e0ea6b646bac.png)

but  Xaml window background does not match IDE：
![image](https://user-images.githubusercontent.com/37654563/47255040-04c87480-d49d-11e8-9a87-2523f4f9b372.png)
thank you！

**Comment by buchizo** [comment]
@TobiasTao 

XAML editor window is special window compare than text editor window. I can exclude it from background image target, but it window can't set to ransparent. If I modify this issue, you will see Visual Studio's background color (e.g. black #FF000000) on XAML editor.
