### ISSUE TITLE
Background turns black when set Expand to Ide to true

### ISSUE THREAD

**Issue by Moralde-Sama** [buchizo/ClaudiaIDE#37]
when false
![image](https://user-images.githubusercontent.com/41711381/52162671-70fc7a80-2712-11e9-9623-a064d9a74d34.png)
when true
![image](https://user-images.githubusercontent.com/41711381/52162679-912c3980-2712-11e9-9772-0860f8d392ac.png)

**Comment by buchizo** [comment]
'Expand to IDE' option should set to transparent on text editor window (EnvironmentBackground) using ColorThemeEditor, because background image behind text editor window and other window/parts.

* [How to expand to IDE](https://github.com/buchizo/ClaudiaIDE#how-to-expand-to-ide)

**Comment by Moralde-Sama** [comment]
I already did it long time ago but it seems yesterday it back to default.

![image](https://user-images.githubusercontent.com/41711381/52171453-64226a00-2798-11e9-9ba6-5f5410ae382d.png)
![image](https://user-images.githubusercontent.com/41711381/52171462-7f8d7500-2798-11e9-9e8b-6e1271261a35.png)
![image](https://user-images.githubusercontent.com/41711381/52171466-98962600-2798-11e9-9186-797f4150541d.png)
![image](https://user-images.githubusercontent.com/41711381/52171476-afd51380-2798-11e9-961c-ee0410beeaf6.png)
![image](https://user-images.githubusercontent.com/41711381/52171481-bfecf300-2798-11e9-9449-76d240208303.png)
![image](https://user-images.githubusercontent.com/41711381/52171486-d72be080-2798-11e9-9ae3-b7eaab66c986.png)

![image](https://user-images.githubusercontent.com/41711381/52171495-00e50780-2799-11e9-9c46-dae1337d9453.png)

btw Im using Visual Studio 2017  Version: 15.9.4

**Comment by buchizo** [comment]
@Moralde-Sama 

I understood this bug in ver2.0.0.

**Comment by buchizo** [comment]
I fixed this issue, but background image is shows after few sec from startup of VS, because extension package should require as background load.
