### ISSUE TITLE
感谢作者不离不弃的更新！

### ISSUE THREAD

**Issue by sfc9982** [buchizo/ClaudiaIDE#41]
本以为弃坑了，回来一看还在更新，VS2019已经开始测试，希望ClaudiaIDE永生不息，造福Coder！

**Comment by buchizo** [comment]
Thank you so much. :)

**Comment by sfc9982** [comment]
> Thank you so much. :)

私はあなたが今日本のユーザーであることを実感します。とにかく、私のお気に入りの女の子コーディングを見てくれてありがとう。
