### ISSUE TITLE
The ext ignore the settings

### ISSUE THREAD

**Issue by sfc9982** [buchizo/ClaudiaIDE#42]
When I change the setting of the ext, it still show the default background, I also change other setting, The result show the config in Visual Studio is not work.
I have tried re-install Visual Studio and the plugin and use it on another PC, it shows it's not plugin's problem.
I just want to know what may cause my config not be apply from the plugin's design.
It will be helpful if you can provide me with the path of the log file.
Thanks.

**Comment by sfc9982** [comment]
I replaced the plugin's image in Extensions root, now it can display my own image but I cannot adjust it.
C:\Users\XXX\AppData\Local\Microsoft\VisualStudio\16.0_d7768593\Extensions\00nmx3ea.mj1\Images\background.jpg

**Comment by sfc9982** [comment]
And it looks like that your cute ext only listen to the config.txt in the folder above.
QwQ

**Comment by sfc9982** [comment]
@buchizo

**Comment by sfc9982** [comment]
Here is my VS info
Microsoft Visual Studio Enterprise 2019 Preview
版本 16.0.0 Preview 3.0
VisualStudio.16.Preview/16.0.0-pre.3.0+28608.199
Microsoft .NET Framework
版本 4.7.03062

已安装的版本: Enterprise

Visual C++ 2019   00435-10000-00000-AA071
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.0.12185.18740
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.0.12185.18740
Azure App Service Tools v3.0.0

C# 工具   3.0.0-beta3-19105-04+f9fc5ea40f861ac30e7ad1a322b7517d4af5d47b
IDE 中使用的 C# 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。

ClaudiaIDE   2.1.0
This extension change the background image of editor.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ 向导   1.0
Microsoft Visual C++ 向导

Microsoft Visual Studio VC 软件包   1.0
Microsoft Visual Studio VC 软件包

NuGet 包管理器   5.0.0
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 http://docs.nuget.org/。

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage 扩展   1.0
ResourcePackage Visual Studio 扩展详细信息

ResourcePackage 扩展   1.0
ResourcePackage Visual Studio 扩展详细信息

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic 工具   3.0.0-beta3-19105-04+f9fc5ea40f861ac30e7ad1a322b7517d4af5d47b
IDE 中使用的 Visual Basic 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。

Visual Studio Code 调试适配器主机包   1.0
用于在 Visual Studio 中托管 Visual Studio Code 调试适配器的互操作层

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

适用于 Google Test 的测试适配器   1.0
启用带有针对 Google Test 编写的单元测试的 Visual Studio 测试工具。扩展安装目录中提供了使用条款和第三方通知。

**Comment by buchizo** [comment]
@sfc9982 

Could you share activitylog?
"%userprofile%\AppData\Roaming\Microsoft\VisualStudio\16.0_xxxx\ActivityLog.xml"

**Comment by buchizo** [comment]
If this ext did run on VS2019 Preview 2.x, I guess this issue's reason from localization on VS, personally. VS2019 preview 3 was started provide a language pack. This extension's option page can support some languages. default en-US and others is ja-JP, zh-CN. In my pc that's  ja-JP is default, but my extension work fine. If you can change to other language (e.g. en-US) on VS, could you try it?

**Comment by sfc9982** [comment]
> If this ext did run on VS2019 Preview 2.x, I guess this issue's reason from localization on VS, personally. VS2019 preview 3 was started provide a language pack. This extension's option page can support some languages. default en-US and others is ja-JP, zh-CN. In my pc that's ja-JP is default, but my extension work fine. If you can change to other language (e.g. en-US) on VS, could you try it?

It works perfectly on another computer with zh_CN lang pack, so it maybe my PC's problem. @buchizo

**Comment by sfc9982** [comment]
[ActivityLog.txt](https://github.com/buchizo/ClaudiaIDE/files/2875974/ActivityLog.txt)

I noticed it tells an error that;
"<description>System.IO.FileNotFoundException: &#x672A;&#x80FD;&#x627E;&#x5230;&#x6587;&#x4EF6;&#x201C;C:\USERS\CYA\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D7768593\EXTENSIONS\00NMX3EA.MJ1\config.txt&#x201D;&#x3002;&#x000D;&#x000A;&#x6587;&#x4EF6;&#x540D;:&#x201C;C:\USERS\CYA\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D7768593\EXTENSIONS\00NMX3EA.MJ1\config.txt&#x201D;&#x000D;&#x000A;   &#x5728; System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)&#x000D;&#x000A;"
on line #856
It looks like the plugin is loading the config file from an non-exist path.
And the real path is 
"C:\Users\CYA\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_D7768593\Extensions\q5kpq20k.uca"

**Comment by sfc9982** [comment]
ActivityLog is an older log file.

**Comment by sfc9982** [comment]
But I know these down here.
1. When I change settings, it do nothing to config.txt.
2. The plugin load config.txt on boot, and it's needed.
3. When I change settings in config.txt manually, it can display my custom background again.
4. After the install, config.txt is the same as in your repo.

**Comment by buchizo** [comment]
ClaudiaIDE read settings from config.txt at first time. Otherwise, config.txt is use when settings doesn't load from VS option page.

if your activitylog is an older, could you retry run VS with /log args.

https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe?view=vs-2017

**Comment by buchizo** [comment]
@sfc9982 

If VS is not correct, you can reset your VS with /ResetUserData args. But this args is delete your settings/data as follows:

https://stackoverflow.com/questions/47823385/what-does-visual-studio-devenv-exe-resetuserdata-do-exactly

**Comment by sfc9982** [comment]
I give up.
Maybe I should buy a new workstation tu use it.
This computer has been tortured by years.
Thank for your patient help and you friendly.
