### ISSUE TITLE
when the mouse enter collapse region,exist bug,part background image be covered

### ISSUE THREAD

**Issue by qwerty1874** [buchizo/ClaudiaIDE#43]

**Comment by buchizo** [comment]
Hmm.. It's by my design. This extension will set image order to behind possible. If you want to image order to front than region, etc, I can fix that. But I'm imagine some problems. For example, image is show over than some text, layer and others. I think that is not confortable. Visual Studio can support image/layer order, but it is indication. I can not care for all Visual Studio's layers like as Roslyn, diff view, or something.

If you want to that, could you modify order after clone/fork this repository for your own extension?

https://github.com/buchizo/ClaudiaIDE/blob/d98a976ce772ee41e57c92ff6f0f27948ef21cff/ClaudiaIDE/ClaudiaIDEFactory.cs#L34

**Comment by buchizo** [comment]
I've tried other layer order, but I'm not found perfect order because I'm not enough have times and  some situations. Personally I think this is good order as follows:

[Order(Before = "TextContentLayer")]

* But it's possible hangs when show peek view in my case.

**Comment by qwerty1874** [comment]
@buchizo 
-_-|||
Thank for the reply,If no more user submit this issues,don't modify please,and then ignore my issues.




I'm so sorry to take up of your time.
Thank again.
