### ISSUE TITLE
ASP .NET text Background is full transparent.

### ISSUE THREAD

**Issue by FredYakumo** [buchizo/ClaudiaIDE#44]
![QQ截图20190511032625](https://user-images.githubusercontent.com/22619763/57551826-9a294880-739c-11e9-9e05-1727025631e2.jpg)

**Comment by buchizo** [comment]
@FredYakumo

Could you tell me more details?

**Comment by buchizo** [comment]
@FredYakumo 
I guess background image can expand to line number part in ver 2.2.0.

**Comment by FredYakumo** [comment]
ok, waiting for update.
