### ISSUE TITLE
画像がスクロールバーに隠れてしまいます

### ISSUE THREAD

**Issue by Hajime-Sasaki** [buchizo/ClaudiaIDE#49]
バージョン2.2.0 VS2019で現象確認。
垂直方向の基準位置 Bottom とした際の画像の下部分、水平方向の基準位置 Right とした際の画像の右部分が、スクロールバーに隠れてしまいます。
![screenshot](https://user-images.githubusercontent.com/31677278/57999649-1ba57700-7b11-11e9-9449-9fd39f040956.png)

同様に、水平方向の基準位置 Left とした際の左側がブレークポイント表示のバーに隠れてしまいます。

**Comment by buchizo** [comment]
2.2.0でちらつき防止用に表示位置を変更した影響です。行番号なども含めた全体の背景に設定したので全面のスクロールバーなどの後ろの表示になります。（2.2.0の仕様です）
※そのかわり2.2.0だと行番号の部分も画像が出るようになったのですが…
とはいえ2.2.0でも完全にちらつきが収まってないので修正も含めて対応を考えているところです

**Comment by buchizo** [comment]
2.2.x の挙動（行番号まで背景表示、スクロールバーは前面に（背景画像が隠れる））を仕様にします。

※ ViewMap（スクロールバー）を透過にする方法もあります。 https://stackoverflow.com/questions/37074567/change-the-color-of-the-scroll-bar-in-map-mode-visual-studio-2015

**Comment by buchizo** [comment]
see also: #54
