### ISSUE TITLE
自带一个灰色的底层？

### ISSUE THREAD

**Issue by KuHai-A** [buchizo/ClaudiaIDE#59]
如下图所示，①③处背景颜色相同，但是和②的颜色有明显差异，即使我将纯文本的背景色设置为白色，②仍然不变。
如果我将ClaudiaIDE设置为不启用，那么①②③的背景色就完全相同了。
（①为codemap插件，背景色设置的与文本编辑区一样，所以正常来说，②应该和①的背景色相同；③为xaml编辑区的背景色，是正常的）
![1](https://user-images.githubusercontent.com/37091493/59270603-73ed1600-8c84-11e9-8fe2-53dcf04fb52b.png)
![2](https://user-images.githubusercontent.com/37091493/59270631-8a936d00-8c84-11e9-9c06-9ed8c641e9db.png)

这是bug还是我某些地方设置错误？

**Comment by buchizo** [comment]
This is by design now. ClaudiaIDE change to new behavior due from 2.2.x. Normally, ClaudiaIDE avoid background color in normal text editor. (I don't know that can fix, yet.)
Some spacific editor like as XAML editor isn't normal behavior of ClaudiaIDE. That can support background color.

**Comment by KuHai-A** [comment]
> This is by design now. ClaudiaIDE change to new behavior due from 2.2.x. Normally, ClaudiaIDE avoid background color in normal text editor. (I don't know that can fix, yet.)
> Some spacific editor like as XAML editor isn't normal behavior of ClaudiaIDE. That can support background color.

那我有办法在不安装color Theme Editor这类插件的前提下，在normal text editor中修改背景色吗？因为ClaudiaIDE的背景色太灰色了，看起来很别扭

**Comment by buchizo** [comment]
Hmm, could you tell me your settings about background color and theme color?

**Comment by KuHai-A** [comment]
> Hmm, could you tell me your settings about background color and theme color?

dark theme，background color is default

**Comment by buchizo** [comment]
For example:

![image](https://user-images.githubusercontent.com/1254213/59363701-8e9cb900-8d70-11e9-8277-2f173392ecbe.png)
![image](https://user-images.githubusercontent.com/1254213/59363752-a2481f80-8d70-11e9-9fd6-0dc41bc4447a.png)

That screenshot is dark theme and background color is default using ClaudiaIDE 2.2.5.
Sorry I'm not sure your case.

> ClaudiaIDE的背景色太灰色了

**Comment by KuHai-A** [comment]
> For example:
> 
> ![image](https://user-images.githubusercontent.com/1254213/59363701-8e9cb900-8d70-11e9-8277-2f173392ecbe.png)
> ![image](https://user-images.githubusercontent.com/1254213/59363752-a2481f80-8d70-11e9-9fd6-0dc41bc4447a.png)
> 
> That screenshot is dark theme and background color is default using ClaudiaIDE 2.2.5.
> Sorry I'm not sure your case.
> 
> > ClaudiaIDE的背景色太灰色了

yes，我的这两处的背景和你一模一样，但明显右侧的有一层模糊的灰色底层，我想让右侧的背景变成左侧的xaml背景，有办法吗

**Comment by buchizo** [comment]
Sorry, could you share your screenshot about that details?

> 但明显右侧的有一层模糊的灰色底层

**Comment by lurenjiayibingding** [comment]
> > This is by design now. ClaudiaIDE change to new behavior due from 2.2.x. Normally, ClaudiaIDE avoid background color in normal text editor. (I don't know that can fix, yet.)
> > Some spacific editor like as XAML editor isn't normal behavior of ClaudiaIDE. That can support background color.
> 
> 那我有办法在不安装color Theme Editor这类插件的前提下，在normal text editor中修改背景色吗？因为ClaudiaIDE的背景色太灰色了，看起来很别扭

请问，最后找到解决方案了嘛？

**Comment by buchizo** [comment]
Maybe latest version (currently 3.1.23) is no problem.

![image](https://github.com/buchizo/ClaudiaIDE/assets/1254213/cb7b6e0c-4d3a-4169-87a7-75ce940313a1)
![image](https://github.com/buchizo/ClaudiaIDE/assets/1254213/9e8941de-82a2-47e0-bb93-5b575cb0f274)

**Comment by lurenjiayibingding** [comment]
> Maybe latest version (currently 3.1.23) is no problem.
> 
> ![image](https://private-user-images.githubusercontent.com/1254213/287459744-cb7b6e0c-4d3a-4169-87a7-75ce940313a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MDc3MzMsIm5iZiI6MTcwMTYwNzQzMywicGF0aCI6Ii8xMjU0MjEzLzI4NzQ1OTc0NC1jYjdiNmUwYy00ZDNhLTQxNjktODdhNy03NWNlOTQwMzEzYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMTI0MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZjMzRjMzhhNjBhNGRlMDUyOTE0YzQ2ODQ4MGVhN2YzYzg4YThkMjVhODY3ZjZiZjJlODMzMTg3NjlhNTZiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NU3re1AQP3ZtUKALcgnuxl_9ici_Bgh1gMu-Nnlb1Yk) ![image](https://private-user-images.githubusercontent.com/1254213/287459754-9e8941de-82a2-47e0-bb93-5b575cb0f274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MDc3MzMsIm5iZiI6MTcwMTYwNzQzMywicGF0aCI6Ii8xMjU0MjEzLzI4NzQ1OTc1NC05ZTg5NDFkZS04MmEyLTQ3ZTAtYmI5My01YjU3NWNiMGYyNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMTI0MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY0NmJjNmJjOTNiYzg3MTBiM2QyN2I5M2VkZDIzYTMzNzFhZDZmM2Q0N2UwYTk4Mzg5NzU0NmU3OTY1YjBlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Xc9npYUUK1yJ7WhVgNkbmPsZd7pfrYfJiu2Z4f69x0M)

Thanks to the author for his selfless dedication
