### ISSUE TITLE
Wrong background color in text editor

### ISSUE THREAD

**Issue by nyanpasu64** [buchizo/ClaudiaIDE#60]
With this extension enabled, and "color theme" extension set to Dark, the background of my text editor is light gray `#2d2d30` (picked up via ShareX) instead of near-black `Text Editor → Plain Text → Background = FF1E1E1E`. There are a lot of 2d2d30 in the theme, and I don't know which is being used. Maybe I could download a decent text editor and binary-search by editing half the 2d2d30's in the color theme and seeing if my editor background changes..

**Comment by buchizo** [comment]
@jimbo1qaz 

In ver 2.2.x, TextBackground color is "Environment -> Window" of ColorTheme Editor.

For example:
![image](https://user-images.githubusercontent.com/1254213/61920660-53a7bb00-af95-11e9-83e4-f7fe84590711.png)

If you would like to change background, you can try modify Encironment WIndow color in ColorThemeEditor.

**Comment by jimbo1qaz** [comment]
Is there a specific reason the text background uses "Environment → Window" instead of "Plain Text → Background" (which is the color used without the extension installed)?

**Comment by buchizo** [comment]
@jimbo1qaz 

Current implementation, this extensions should change to transparent background of plain text background color. (because I fixed flicker issue when previous versions, I large modified code.)
In this case, we seeing background that is Environment->window color. If I'm got great implementations, I'll update it.

**Comment by SimplyPancake** [comment]
@buchizo Is it possible for you to provide the dark theme you are using?

**Comment by buchizo** [comment]
@SimplyPancake Sorry I'm not use custom dark theme now. Could you see also [How to expand to IDE](https://github.com/buchizo/ClaudiaIDE/blob/master/README.md) section?
