### ISSUE TITLE
*.aspx file doesn't match with config

### ISSUE THREAD

**Issue by hoangitc500** [buchizo/ClaudiaIDE#61]
Hi!
I'm using VS2015
My config does not apply with *.aspx file

![image](https://user-images.githubusercontent.com/16145521/62039061-21aa8900-b221-11e9-81a9-f734f2be13ca.png)

![image](https://user-images.githubusercontent.com/16145521/62039084-2e2ee180-b221-11e9-952b-a20a9579044f.png)

You can see in picture, background in background with *.aspx file!

**Comment by buchizo** [comment]
@hoangitc500 

Some file types of editor is different than normal text editor. For example, .aspx, .xaml. ClaudiaIDE can't set to transparent yet, it's by design now. If I'm got great implements, I'll update it.

**Comment by hoangitc500** [comment]
I understand! Thank so much for helping!
