### ISSUE TITLE
Offset image when wide scrollbar is on

### ISSUE THREAD

**Issue by AnkoBG** [buchizo/ClaudiaIDE#62]
Hi, is it possible to offset the image when map mode for vertical scrollbar is on.

Below is where the settings for the scrollbar are located:

![ClaudiaSettings](https://user-images.githubusercontent.com/33812357/70322588-27e5ed00-1833-11ea-866a-94241e43f3e9.PNG)

And how it looks like currently:

![ClaudiaCut](https://user-images.githubusercontent.com/33812357/70322557-1270c300-1833-11ea-9d75-b5712c8a155a.PNG)

**Comment by buchizo** [comment]
I add position property.

![image](https://user-images.githubusercontent.com/1254213/71540195-b0673180-298a-11ea-9ef5-a46dd8f3563b.png)

I guess you can set 0.1 -0.2 to that.

**Comment by AnkoBG** [comment]
Thanks, works great!
