### ISSUE TITLE
considered supporting video😄😄

### ISSUE THREAD

**Issue by rickerliang** [buchizo/ClaudiaIDE#64]
Have the authors considered supporting video? Imagine watching the animate while coding, which is exciting😄😄

**Comment by buchizo** [comment]
Oh, that's crazy feature... I will consider it..

**Comment by KatPurpy** [comment]
have you done considering yet?

**Comment by BOBJohnson** [comment]
I would like this feature as well.

**Comment by Heppymon** [comment]
Sounds great! I wonna see Rick Astley in my VS 🌝

**Comment by buchizo** [comment]
now developing...

https://user-images.githubusercontent.com/1254213/128611112-94444f31-a998-4273-ba27-6889f74bd242.mp4

**Comment by Ferrarie** [comment]
能放视频 , 这可太骚了

**Comment by AraHaan** [comment]
Will we be able to expand the video to the full IDE eventually to fill the entire area of the IDE eventually?

**Comment by AraHaan** [comment]
@buchizo what is the status atm on this?

**Comment by buchizo** [comment]
> Will we be able to expand the video to the full IDE eventually to fill the entire area of the IDE?

Maybe possible, but I'm not decide yet because possibility some problems like as performance.

> what is the status at the moment on this?

Now in development but slowly too.

**Comment by AraHaan** [comment]
> > Will we be able to expand the video to the full IDE eventually to fill the entire area of the IDE?
> 
> Maybe possible, but I'm not decide yet because possibility some problems like as performance.
> 
> > what is the status at the moment on this?
> 
> Now in development but slowly too.

Btw I am currently working on a new VS2022 Dark Transparent theme that is with a purple accent color.

However I need to figure out the color on the Color theme designer for VS2022 for the ``WMDocumentGroupContainerControl`` item on their wpf window in the IDE (this is the background part of the IDE that I have left to adjust the transparency on (other than the toolbar background on the main IDE window). After that it should be possible for me to ship it in the Visual Studio marketplace where you can suggest it for those using VS2022.

**Comment by jacob-machado-bwtek** [comment]
Any Update on this? I see that ClaudiaIDE already accepts .gif filetypes, but no animation yet?

**Comment by drWack** [comment]
Any Update on this? I see ClaudiaIDE accepts .gif files, but not animating them yet.

**Comment by buchizo** [comment]
experimental support about animation gif and mp4 video for 3.1.16
