### ISSUE TITLE
Can you share your background images.

### ISSUE THREAD

**Issue by heroboy** [buchizo/ClaudiaIDE#70]

**Comment by buchizo** [comment]
What is this issue means? I could not understand it.

**Comment by heroboy** [comment]
Sorry if it is not suitable.
I want a place let people share their background images.
If it is not suitable, you can close this.

**Comment by buchizo** [comment]
In general, the redistribution of image files by third parties needs to go beyond the rights of the creator and the law.
It would be better to refer to a service like Pixiv.

Whatever the content is, it's not an Issue of this extension, so I'll close it.

**Comment by n0099** [comment]
If you are talking about the demo image used in the readme of this repo:
[![](https://raw.githubusercontent.com/buchizo/ClaudiaIDE/c791eb008b6c1aa0aa9fb6e93553f2b76b6bed3e/Images/example01.png)](https://github.com/buchizo/ClaudiaIDE/blob/c791eb008b6c1aa0aa9fb6e93553f2b76b6bed3e/Images/example01.png)

She is called as `Claudia Madobe`(so this extension is named after her), and appeared in manga `Cloud Girl - Mado to Kumo to Aoi Sora-`(`Cloud Girl: Windows, Clouds, and Azure Skies`)

A long list of archived resources I've found:

- https://asiajin.com/blog/2011/05/cloud-girl-microsoft-windows-azure-manga-promotion/
- https://www.animenewsnetwork.com/interest/2011-05-23/microsoft-launches-cloud-girl-manga-for-windows-azure

- https://myanimelist.net/character/155654/Claudia_Madobe
- https://www.ostan-collections.net/wiki/index.php/Windows_Azure

- https://www.facebook.com/claudia.azure
- http://web.archive.org/web/20130521022736/https://twitter.com/claudia_azure
- http://web.archive.org/web/20160306030953/https://twitter.com/Claudia_Azure
- http://web.archive.org/web/20170409204459/https://twitter.com/Claudia_Azure
- http://web.archive.org/web/20190329131804/https://twitter.com/Claudia_Azure

- https://www.youtube.com/watch?v=5tQNjAw7PjU
- https://yande.re/post?tags=claudia_madobe
- https://www.ebay.com/itm/354230602768
- https://lumikatto.residentialruin.online/product/12406381237.html
- https://bluebluewave.wordpress.com/2011/11/22/microsoft-windows-azure-cloud-girl-claudia-sound-pack/
- http://web.archive.org/web/20140906034800/http://ostan-collections.net/imeeji/thumbnails.php?album=294
- https://forum.lowyat.net/topic/2545297/all
- https://ostan-collections.net/forum/index.php?topic=1475.60
- https://danbooru.donmai.us/posts?tags=claudia_madobe+&z=5
- https://danbooru.donmai.us/pools/3613
![image](https://user-images.githubusercontent.com/13030387/219872976-570f5271-e79f-4f1c-bdf0-52d0433f6959.png)
![image](https://user-images.githubusercontent.com/13030387/219872978-c989e66a-e1c0-4ee9-a06f-b0c0977c715c.png)
![image](https://user-images.githubusercontent.com/13030387/219872985-e0ca48ad-1b4a-45ce-8011-5b32641cc4bf.png)
- https://web.archive.org/web/20170919171305/https://msdn.microsoft.com/ja-jp/windowsazure/claudia
- https://web.archive.org/web/20120116104347/http://msdn.microsoft.com/ja-jp/windowsazure/hh184191
- https://web.archive.org/web/20170629145633/https://msdn.microsoft.com/ja-jp/windowsazure/gg194745
- https://www.ostan-collections.net/forum/index.php/topic,1475.90.html
- https://www.youtube.com/watch?v=ONlQ7t6t9Jw
