### ISSUE TITLE
SingleEach Random Select

### ISSUE THREAD

**Issue by stricq** [buchizo/ClaudiaIDE#71]
I just recently discovered the SingleEach option and I really love it.  I would like to suggest an enhancement to this mode to randomly select the images skipping any currently in use.  I have over 500 images in the directory and using the images in the same order means that I will never see 98% of the images available.

Perhaps a SingleEach config section in the options where random selection can be set by the user.

**Comment by buchizo** [comment]
ver 2.2.13 support random images when choose SingleEach type. if you want to randomize,  "Shuffle Slideshow" option set to True.
