### ISSUE TITLE
Another one problem

### ISSUE THREAD

**Issue by Arko-N** [buchizo/ClaudiaIDE#76]
*Hi there, dev-team.*

And ***problem*** is... :

> After closing the IDE, sometimes it's can **reopen**,
> and **show notification** that closing was **incorrect** and recommend **turn-off** yours extention.
> *(That is correct, turning it off helps. But I can't agree with this stuff!.. so wrote this issue).*
> 
> Notification will at starting **at each time**, noway how was IDE closed.
> 
> **I hope that you'll fix that.**

Kind regards,
*Some User (_))*

**Comment by buchizo** [comment]
Could you share activitylog.xml?
 
* how to create activitylog.xml
 
1. run devenv.exe (Visual Studio) with /log option as follows:
 
![image](https://user-images.githubusercontent.com/1254213/117522743-07096480-aff0-11eb-8a04-1ab436bb47a3.png)
 
2. open some files (retry your problem).
 
3. Close Visual Studio. And pick up activitylog.xml from as follows path:
 
%appdata%\Microsoft\VisualStudio\16.0_xxxxx\ActivityLog.xml
 
![image](https://user-images.githubusercontent.com/1254213/117522735-fe189300-afef-11eb-8eee-c9e5a4ebd2ee.png)
 
* 16.0_xxxxx replace to your environment

**Comment by Arko-N** [comment]
> ## *This should be what is need.*
> *(I look forward to confidentiality)*

---

[XML-file on GoogleDrive](https://drive.google.com/file/d/1cP_qSygeq5_aKoEuHTyaA4aRxDQtZDhQ/view?usp=sharing)

---

> **I was able to repeat the error of reopening the IDE only once and failed to determine the pattern.**
> **But the "previous session unexpectedly ended" message stably appears on every startup.**

**Comment by buchizo** [comment]
@Arko-N I checked activitylog.xml, but I could not find log about this ClaudiaIDE extension and any warning/error log in xml file.

Is your problem from this extension? This extension disabled after turn-off in VS notification bar?
And your VS version is one year old, if possible could you update it?

**Comment by Arko-N** [comment]
> - I updated VS. This didn't change the situation.
> - Restarting the IDE after closing most likely occurs on the first shutdown after reconnecting the extension.
> - And, yap, the problem clearly arises in ClaudiaIDE, because when it is disabled, the notification doesn't appear.
> - The extension is correctly disabled both through the notification bar and through the extensions menu.

> *I want to say that the problem itself is not critical. Everything works.*
> *It's just that since such an unusual notification appears, then I decided that you, the developers, should know about this.*
> *All the same, behind this there may be something more serious, I just didn't run into it.*

**Comment by buchizo** [comment]
@Arko-N 
Thank you for your information. I rechecked log in my env. I fix this problem on new version [2.2.17](https://github.com/buchizo/ClaudiaIDE/releases/tag/Release2.2.17), maybe.
