### ISSUE TITLE
Request to add anti-aliasing features to this plugin

### ISSUE THREAD

**Issue by Sg4Dylan** [buchizo/ClaudiaIDE#8]
I can't let my pic fill the window without aliasing.
If you can, could you please add anti-aliasing features to this plugin?
Or add picture padding feature?

**Comment by buchizo** [comment]
Could you show sample to me about feature of aliasing?
E.g. that feature can fill picture (pinch in / pinch out) to editor background.

**Comment by buchizo** [comment]
![image](https://cloud.githubusercontent.com/assets/1254213/12384128/e9ce4e44-bdf1-11e5-97c9-862fba4f9c7d.png)
E.g. strech, strech-fill and strech-fit...

**Comment by Sg4Dylan** [comment]
Original picture: 
[https://i.imgur.com/Cq8hctY.jpg](http://i.imgur.com/Cq8hctY.jpg)
![https://i.imgur.com/Cq8hctY.jpg](http://i.imgur.com/Cq8hctY.jpg)

Actual result:
[http://i.imgur.com/SBpTAwA.png](http://i.imgur.com/SBpTAwA.png)
![http://i.imgur.com/SBpTAwA.png](http://i.imgur.com/SBpTAwA.png)

Problem 1:
Can not aito streth-fill into IDE.
Problem 2:
There are many sawtooth-like things on edge

Sample: 
[http://www.dl-c.com/Resampling.pdf](http://www.dl-c.com/Resampling.pdf)
or
[http://johncostella.webs.com/magic/](http://johncostella.webs.com/magic/)

**Comment by buchizo** [comment]
![image](https://cloud.githubusercontent.com/assets/1254213/12517855/64f3f798-c178-11e5-9a36-325a273217b0.png)
Problem #1: I can impliment about stretch-fill feature. However that feature depend on Image control. If you use strech-fill, you might have jaggy.
Problem #2: ClaudiaIDE's background image depend on Visual Studio editor settings. If your editor's zoom level is 100%, you can show original image. (not have jaggy!)
zoom is automatic. I can't control it.

A better how-to: You might prepare image that is match (or than large) in your IDE's window size.

**Comment by buchizo** [comment]
This feature always depend on Visual Studio. In this case, this exchange can't control (maybe).
