### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by buchizo** [buchizo/ClaudiaIDE#81]

**Comment by buchizo** [comment]
pre release [3.0.0.1](https://github.com/buchizo/ClaudiaIDE/releases/tag/pre-release-3.0.0.1-2)

**Comment by buchizo** [comment]
pre release [3.0.0.2](https://github.com/buchizo/ClaudiaIDE/releases/tag/pre-releqse-3.0.0.2)

**Comment by buchizo** [comment]
Hmm... I will drop off support for VS2017 because I couldn't resolve conflict about Shell.15 NuGet package.

**Comment by buchizo** [comment]
pre release [3.0.0.3](https://github.com/buchizo/ClaudiaIDE/releases/tag/pre-release-3.0.0.3)

**Comment by oscartorres9** [comment]
> pre release [3.0.0.3](https://github.com/buchizo/ClaudiaIDE/releases/tag/pre-release-3.0.0.3)

some exception in vs2019，release 3.0.0.3
throw filenotfoundexception

**Comment by buchizo** [comment]
@oscartorres9 Is that  Microsoft.VisualStudio.Shell.15?

**Comment by oscartorres9** [comment]
> @oscartorres9 Is that Microsoft.VisualStudio.Shell.15?

![image](https://user-images.githubusercontent.com/17999586/122640140-5d5ddd00-d130-11eb-9c3d-9165c23cea89.png)

**Comment by oscartorres9** [comment]
[ActivityLog.xml.txt](https://github.com/buchizo/ClaudiaIDE/files/6680545/ActivityLog.xml.txt)
error log files, hope help

**Comment by buchizo** [comment]
@oscartorres9 I guess your VS2019 is less than 16.10.2. I'd downgrade using NugetPackage for 16.0. Could you try [this pre-release 3.0.0.4 version](https://github.com/buchizo/ClaudiaIDE/releases/tag/pre-release-3.0.0.4) ?

**Comment by oscartorres9** [comment]
> @oscartorres9 I guess your VS2019 is less than 16.10.2. I'd downgrade using NugetPackage for 16.0. Could you try [this pre-release 3.0.0.5 version](https://github.com/buchizo/ClaudiaIDE/releases/tag/pre-release-3.0.0.5) ?

it's fixed, big thanks!!
