### ISSUE TITLE
Horizontal and Vertical ViewBox Position not Honored in XAML Editor Window

### ISSUE THREAD

**Issue by lumberjack4** [buchizo/ClaudiaIDE#84]
When specifying the `Image horizontal position in ViewBox` and `Image vertical position in ViewBox` properties in settings, the background image location does not update in the XAML editor window like it does in the code editor window.

Settings:
![image](https://user-images.githubusercontent.com/2118206/123833455-f7a9e780-d8cb-11eb-9db4-f6b2cb5f30d2.png)

Code Editor:
![image](https://user-images.githubusercontent.com/2118206/123833507-04c6d680-d8cc-11eb-942e-ed468c4b7957.png)

XAML Editor:
![image](https://user-images.githubusercontent.com/2118206/123833576-1d36f100-d8cc-11eb-8c6c-d662ca0267f9.png)

**Comment by buchizo** [comment]
fix done.

- [ver 3.0.0.6](https://github.com/buchizo/ClaudiaIDE/releases/tag/Release3.0.0.6)
- or [ver 2.2.19](https://github.com/buchizo/ClaudiaIDE/releases/tag/Release2.2.19)
