### ISSUE TITLE
There is something wrong.

### ISSUE THREAD

**Issue by Marskey** [buchizo/ClaudiaIDE#9]
I am using win10 on mac,  IDE is vs2012.
  When I scroll the screen, the image will flicker. Dose it is not support retina?

**Comment by buchizo** [comment]
Currently, this extension is support the Retina display, probably. However the flicker will be occurred on some environments by the Visual Studio.

When you scroll editor, The editor's size become change to new virtual position (top, left, height and width...) of editor by the Visual Studio. This extension follow new position (and size). But absolutely misalignment occurs. It's reason about flicker issue.

I guess, this problem depend on the Visual Studio. However I'd like to fix this issue, I not have any good ideas... :(

**Comment by Marskey** [comment]
thanks 4 give an answer. by the way, why not try program one more plugin 4 xcode~ :) i'm just saying
