### ISSUE TITLE
No transparency or background image in latest update

### ISSUE THREAD

**Issue by r2com** [buchizo/ClaudiaIDE#91]
Latest 2022 preview #3 does not give transparency or background image. not working.

**Comment by buchizo** [comment]
@r2com could you provide settings, screenshot and more details?

**Comment by buchizo** [comment]
I guess fixed it of [3.0.0.9](https://github.com/buchizo/ClaudiaIDE/releases/tag/Release3.0.0.9)

**Comment by buchizo** [comment]
this issue occurred in this case as follows:

- ExpandIDE is true
- Start VS2022 without code
