### ISSUE TITLE
Not support Solution Explorer 

### ISSUE THREAD

**Issue by bradlee2018** [buchizo/ClaudiaIDE#92]
vs2019 version 16.11.0
Set expand to IDE true and others setting. Finally solution explorer not show image.
![Uploading QQ截图20210816112807.png…]()

**Comment by buchizo** [comment]
@bradlee2018 
Solution explorer is not editor window. ClaudiaIDE does not set transparency to solution explorer. If you want to show background image of solution explorer and other window, you should set transparency to solution explorer using ThemeEditor or [this extensions[(https://marketplace.visualstudio.com/items?itemName=pengweiqhca.transparency).

**Comment by bradlee2018** [comment]
I followed the content in README.md->Ver 1.24, and found the sample.png. Solution explorer can show image.
![how to expand to IDE](https://user-images.githubusercontent.com/11631788/129532041-01383b50-1d83-4532-ae5c-80cf64beafb8.png)
![sample](https://user-images.githubusercontent.com/11631788/129532044-1a31b7b4-009e-44c0-9a90-5ae8bcba4e00.png)

**Comment by buchizo** [comment]
That was using [Color Theme Editor](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2019ColorThemeEditor).

Alone ClaudiaIDE does not support set transparency for solution explorer.

**Comment by bradlee2018** [comment]
Thank you!
