### ISSUE TITLE
The "Expand to IED" option is no longer functional, the background turns black when selected

### ISSUE THREAD

**Issue by Yz-Leaf** [buchizo/ClaudiaIDE#93]
The "Expand to IED" option is no longer functional, the background turns black when selected

The False state is displayed normally, but the Ture state image will disappear.

**Comment by buchizo** [comment]
I guess fixed it of [3.0.0.9](https://github.com/buchizo/ClaudiaIDE/releases/tag/Release3.0.0.9)

**Comment by Yz-Leaf** [comment]
> [3.0.0.9](https://github.com/buchizo/ClaudiaIDE/releases/tag/Release3.0.0.9)

Already solved, thanks a lot!
